[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aiposematic"
authors = [{name = "Fibo Metavinci", email = "pszdw-75nat-5227i-bha5s-y7lai-pebdq-o2agp-3xho4-hd6z6-emxrd-nqe@dmail.ai"}]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dynamic = ["version", "description"]
dependencies = [
    "matplotlib>=3.7",
    "numpy>=1.24",
    "opencv-python>=4.8",
    "pillow>=10.0",
    "qrcode>=7.4",
    "cryptography>=41.0",
    "scikit-image>=0.21",
    "scipy>=1.11",
]

[project.urls]
Home = "https://github.com/inviti8/aiposematic"
